"""liker

Revision ID: 11697e0996db
Revises: 16f52d1c4d82
Create Date: 2018-04-30 04:16:11.787053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11697e0996db'
down_revision = '16f52d1c4d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liker', sa.String(length=64), nullable=True),
    sa.Column('po', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liker'], ['user.username'], ),
    sa.ForeignKeyConstraint(['po'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    # ### end Alembic commands ###
