"""event location

Revision ID: 611ee77bd793
Revises: 1cdfb7e249ac
Create Date: 2018-04-29 22:54:28.281842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611ee77bd793'
down_revision = '1cdfb7e249ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('location', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'location')
    # ### end Alembic commands ###
